name: Deploy FastAPI to Azure Function

on:
  push:
    branches:
      - staging
      - main

env:
  AZURE_RESOURCE_GROUP: rg-fastapi-${{ github.ref_name }}
  FUNCTION_APP_NAME: fastapi-func-${{ github.ref_name }}
  LOCATION: eastus
  PYTHON_VERSION: "3.10"
  PLAN_NAME: plan-fastapi-${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group (idempotent)
      run: |
        az group create --name $AZURE_RESOURCE_GROUP --location $LOCATION

    # - name: Check if App Plan exists
    #   id: check_plan
    #   run: |
    #     if az functionapp plan show --name $PLAN_NAME --resource-group $AZURE_RESOURCE_GROUP &> /dev/null; then
    #       echo "exists=true" >> $GITHUB_OUTPUT
    #     else
    #       echo "exists=false" >> $GITHUB_OUTPUT
    #     fi

    # - name: Create App Plan (if not exists)
    #   if: steps.check_plan.outputs.exists == 'false'
    #   run: |
    #     az functionapp plan create \
    #       --name $PLAN_NAME \
    #       --resource-group $AZURE_RESOURCE_GROUP \
    #       --location $LOCATION \
    #       --number-of-workers 1 \
    #       --sku F1 \
    #       --is-linux

    - name: Check if Function App exists
      id: check_func
      run: |
        if az functionapp show --name $FUNCTION_APP_NAME --resource-group $AZURE_RESOURCE_GROUP &> /dev/null; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Function App (if not exists)
      if: steps.check_func.outputs.exists == 'false'
      run: |
        az functionapp create \
          --name $FUNCTION_APP_NAME \
          --storage-account $FUNCTION_APP_NAME \
          --resource-group $AZURE_RESOURCE_GROUP \
          --runtime python \
          --runtime-version $PYTHON_VERSION \
          --functions-version 4 \
          --os-type Linux \
          --consumption-plan-location $LOCATION

    - name: Set Environment Variables
      run: |
        az functionapp config appsettings set \
          --name $FUNCTION_APP_NAME \
          --resource-group $AZURE_RESOURCE_GROUP \
          --settings ENV=${{ github.ref_name }}

    - name: Deploy Code
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.FUNCTION_APP_NAME }}
        package: .
